### ISSUE TITLE
kotlinx.coroutines.CoroutinesInternalError Failure from system

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#522] opened 2022-08-08 00:43 UTC
Stacktrace
```
kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for CancellableContinuation(DispatchedContinuation[Dispatchers.Main, Continuation at kotlinx.coroutines.flow.SharedFlowImpl.collect$suspendImpl(SharedFlow.kt:383)@aab070b]){Completed}@47989e8. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
	at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:4)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:27)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7801)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:997)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [CoroutineName(Controller_AlbumViewController), StandaloneCoroutine{Cancelling}@d3bc9fc, Dispatchers.Main]
Caused by: java.lang.RuntimeException: Failure from system
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1729)
	at android.app.ContextImpl.startActivity(ContextImpl.java:1023)
	at android.app.ContextImpl.startActivity(ContextImpl.java:994)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:403)
	at com.github.k1rakishou.chan.Chan.onUnhandledException(Chan.kt:24)
	at com.github.k1rakishou.chan.Chan$$ExternalSyntheticLambda1.uncaughtException(Unknown Source:3)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:10)
	at kotlinx.coroutines.CoroutineExceptionHandlerKt.handleCoroutineException(CoroutineExceptionHandler.kt:3)
	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:2)
	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:14)
	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:28)
	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:2)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:1)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:10)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	... 7 more
Caused by: android.os.TransactionTooLargeException: data parcel size 16693496 bytes
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:540)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3917)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1723)
	... 23 more

```

Additional information
```
------------------------------
Android API Level: 30
App Version: v1.3.13
Phone Model: LENOVO Lenovo TB-J616F
Build type: Release
Flavor type: Stable
isLowRamDevice: false, isLowRamDeviceForced: false
MemoryClass: 256
App running time: 00:00:22.265
------------------------------
Current layout mode: SPLIT
Board view mode: STAGGER
Bottom navigation enabled: true
Prefetching enabled: true
Hi-res thumbnails enabled: true
mediaViewerMaxOffscreenPages: 1
CloudFlare force preload enabled: false
useMpvVideoPlayer: true
userAgent: Mozilla/5.0 (Linux; Android 11; Lenovo TB-J616F Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.129 Safari/537.36
kurobaExCustomUserAgent: KurobaEx v1.3.13
maxPostsCountInPostsCache: 13107
maxAmountOfPostsInDatabase: 75000
maxAmountOfThreadsInDatabase: 12500
diskCacheSizeMegabytes: 256
prefetchDiskCacheSizeMegabytes: 512
diskCacheCleanupRemovePercent: 25
ImageSaver root directory: content://com.android.externalstorage.documents/tree/primary%3ADownload%2FForchins
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
Foreground watcher enabled: true
Watch foreground interval: 60000
Watch foreground adaptive interval: true
Background watcher enabled: true
Watch background interval: 1800000
Filter watch enabled: false
Thread downloader interval: 2700000
Thread downloader download media on metered network: false
------------------------------

```

**Comment by K1rakishou** [comment] 2022-08-16 08:32
Gonna close this one because this is the " android.os.TransactionTooLargeException: data parcel size 16693496 bytes" exception which I have no idea how to reproduce let alone fix.

**Closed by K1rakishou** 2022-08-16 08:32 UTC
Labels: Report
