### ISSUE TITLE
SLOW LOADINGS

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#129] opened 2022-02-18 07:18 UTC
APLLYING FLITER SLOW LOADING NEED TO FIXED IMMEDIATELY
SOME CERTAIN BOARD CAN'T ACCESS CUZ OF THIS
MORE SLOWER THAN SONIC 06 LOADING SCREEN
CAN YOU FIX IT PLEASE?

THANK YOU

**Comment by K1rakishou** [comment] 2022-02-18 08:23
Duplicate of https://github.com/KurobaExReports/Reports/issues/128

**Closed by K1rakishou** 2022-02-18 08:23 UTC
Labels: Report, Duplicate
