### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#239] opened 2022-03-18 09:22 UTC
```=== LOGS(2022-03-18 08:14:55 UTC) ===
E/(16:14:55.327) KurobaEx | Chan: Unhandled exception in thread: main
E/(16:14:55.327) KurobaEx | Chan: DeadSystemException: The system died; earlier logs will point to the root cause


=== STACKTRACE ===
Called from unhandled exception handler.
java.lang.RuntimeException: android.os.DeadSystemException
	at android.view.autofill.AutofillManager.updateSessionLocked(AutofillManager.java:1975)
	at android.view.autofill.AutofillManager.notifyValueChanged(AutofillManager.java:1377)
	at android.widget.TextView.notifyListeningManagersAfterTextChanged(TextView.java:11910)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:11890)
	at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:15166)
	at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1288)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:588)
	at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:11)
	at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:232)
	at androidx.emoji2.text.SpannableBuilder.delete(SpannableBuilder.java:1)
	at android.text.method.BaseKeyListener.backspaceOrForwardDelete(BaseKeyListener.java:376)
	at android.text.method.BaseKeyListener.backspace(BaseKeyListener.java:71)
	at android.text.method.BaseKeyListener.onKeyDown(BaseKeyListener.java:485)
	at android.text.method.QwertyKeyListener.onKeyDown(QwertyKeyListener.java:362)
	at android.text.method.TextKeyListener.onKeyDown(TextKeyListener.java:141)
	at androidx.emoji2.viewsintegration.EmojiKeyListener.onKeyDown(EmojiKeyListener.java:7)
	at android.widget.TextView.doKeyDown(TextView.java:9500)
	at android.widget.TextView.onKeyDown(TextView.java:9272)
	at android.view.KeyEvent.dispatch(KeyEvent.java:3664)
	at android.view.View.dispatchKeyEvent(View.java:14927)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at androidx.core.widget.NestedScrollView.dispatchKeyEvent(NestedScrollView.java:1)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1991)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:963)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1952)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4217)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:1)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:2)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:3)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:4)
	at com.github.k1rakishou.chan.core.base.ControllerHostActivity.dispatchKeyEvent(ControllerHostActivity.kt:1)
	at com.github.k1rakishou.chan.activity.StartActivity.dispatchKeyEvent(StartActivity.kt:3)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:2)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:816)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:7587)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7411)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6788)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6845)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6811)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:7009)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6819)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:7066)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6792)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6845)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6811)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6819)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6792)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:10220)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:10068)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:10024)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessageImpl(ViewRootImpl.java:6405)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:6269)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8641)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
Caused by: android.os.DeadSystemException
	... 81 more


------------------------------
Android API Level: 31
App Version: v1.3.9
Phone Model: samsung SM-A426B
Build type: Release
Flavor type: Stable
isLowRamDevice: false, isLowRamDeviceForced: false
MemoryClass: 256
App running time: 01:13:24.223
------------------------------
Current layout mode: SLIDE
Board view mode: LIST
Bottom navigation enabled: true
Prefetching enabled: false
Hi-res thumbnails enabled: false
mediaViewerMaxOffscreenPages: 1
CloudFlare force preload enabled: false
useMpvVideoPlayer: false
userAgent: Mozilla/5.0 (Linux; Android 12; SM-A426B Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.73 Mobile Safari/537.36
kurobaExCustomUserAgent: KurobaEx v1.3.9
maxPostsCountInPostsCache: 13107
maxAmountOfPostsInDatabase: 75000
maxAmountOfThreadsInDatabase: 12500
diskCacheSizeMegabytes: 256
prefetchDiskCacheSizeMegabytes: 512
diskCacheCleanupRemovePercent: 25
ImageSaver root directory: content://com.android.externalstorage.documents/tree/primary%3AKurobaEX
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
Foreground watcher enabled: true
Watch foreground interval: 60000
Watch foreground adaptive interval: true
Background watcher enabled: true
Watch background interval: 1800000
Filter watch enabled: false
Thread downloader interval: 1800000
Thread downloader download media on metered network: true
------------------------------
```

**Comment by K1rakishou** [comment] 2022-04-01 09:13
Duplicate of https://github.com/KurobaExReports/Reports/issues/246

**Closed by K1rakishou** 2022-04-01 09:13 UTC
Labels: Crash, Duplicate
