### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#57] opened 2022-01-27 21:57 UTC
```=== LOGS(2022-01-27 21:56:55 UTC) ===
D/(15:56:12.643) KurobaEx | HttpCallManager: Request (Chan4ReplyCall, https://sys.4chan.org/pol/post) execution success, took 645.909687ms
D/(15:56:12.646) KurobaEx | Chan4ReplyCall: setChan4CaptchaHeader() newCookie='null', domain='null', wholeCookieHeader='null'
D/(15:56:12.646) KurobaEx | Chan4ReplyCall: setChan4CaptchaHeader() domain is null
E/(15:56:12.646) KurobaEx | Chan4ReplyCall: process() requireAuthentication
D/(15:56:12.647) KurobaEx | PostingServiceDelegate: SiteActions.PostResult.PostComplete(TD{4chan/pol/358443862}) failed to post, response=ReplyResponse{posted=false, errorMessage='null', siteDescriptor=SD{4chan}, boardCode='pol', threadNo=0, postNo=0, password='7ff61300b1db9a45', probablyBanned=false, requireAuthentication=true, rateLimitInfo=null, additionalResponseData=null}
D/(15:56:12.648) KurobaEx | PostingServiceDelegate: emitTerminalEvent(TD{4chan/pol/358443862}, Success(replyResponse=ReplyResponse{posted=false, errorMessage='null', siteDescriptor=SD{4chan}, boardCode='pol', threadNo=0, postNo=0, password='7ff61300b1db9a45', probablyBanned=false, requireAuthentication=true, rateLimitInfo=null, additionalResponseData=null}, replyMode=ReplyModeSendWithoutCaptcha, retrying=false))
D/(15:56:12.648) KurobaEx | LastReplyRepository: onPostAttemptFinished(TD{4chan/pol/358443862}, newCooldownInfo=null)
D/(15:56:12.648) KurobaEx | LastReplyRepository: onPostAttemptFinished(TD{4chan/pol/358443862}, cooldownInfo=CooldownInfo(boardDescriptor=BD{4chan/pol}, currentPostingCooldownMs=0))
D/(15:56:12.648) KurobaEx | LastReplyRepository: endPosting(BD{4chan/pol})
D/(15:56:12.648) KurobaEx | PostingServiceDelegate: runPostWaitQueueLoop(TD{4chan/pol/358443862}) makePostInternal() -> FailedToPost
D/(15:56:12.649) KurobaEx | PostingServiceDelegate: runPostQueueLoop(TD{4chan/pol/358443862}) took 665ms
D/(15:56:12.649) KurobaEx | PostingServiceDelegate: All replies for board BD{4chan/pol} processed, resetting the cooldowns
D/(15:56:12.649) KurobaEx | LastReplyRepository: onPostAttemptFinished(TD{4chan/pol/358443862}, newCooldownInfo=null)
D/(15:56:12.650) KurobaEx | LastReplyRepository: onPostAttemptFinished(TD{4chan/pol/358443862}, cooldownInfo=CooldownInfo(boardDescriptor=BD{4chan/pol}, currentPostingCooldownMs=0))
D/(15:56:12.650) KurobaEx | PostingService: childNotificationUpdates() descriptor=TD{4chan/pol/358443862}, status=com.github.k1rakishou.chan.features.posting.ChildNotificationInfo$Status$Uploaded@4724087
D/(15:56:12.652) KurobaEx | PostingService: childNotificationUpdates() descriptor=TD{4chan/pol/358443862}, status=Error(errorMessage=Authentication required)
D/(15:56:12.653) KurobaEx | ReplyPresenter: processPostingStatusUpdates(TD{4chan/pol/358443862}) -> AfterPosting, status.postResult=Success(replyResponse=ReplyResponse{posted=false, errorMessage='null', siteDescriptor=SD{4chan}, boardCode='pol', threadNo=0, postNo=0, password='7ff61300b1db9a45', probablyBanned=false, requireAuthentication=true, rateLimitInfo=null, additionalResponseData=null}, replyMode=ReplyModeSendWithoutCaptcha, retrying=false)
D/(15:56:12.657) KurobaEx | ReplyPresenter: onPostComplete() requireAuthentication==true replyResponse=ReplyResponse{posted=false, errorMessage='null', siteDescriptor=SD{4chan}, boardCode='pol', threadNo=0, postNo=0, password='7ff61300b1db9a45', probablyBanned=false, requireAuthentication=true, rateLimitInfo=null, additionalResponseData=null}
E/(15:56:12.657) KurobaEx | ReplyPresenter: onPostCompleteUnsuccessful() error: Error posting: Authentication required
D/(15:56:12.659) KurobaEx | ReplyPresenter: processPostingStatusUpdates(TD{4chan/pol/358443862}) consumeTerminalEvent(TD{4chan/pol/358443862})
D/(15:56:12.659) KurobaEx | PostingServiceDelegate: consumeTerminalEvent(TD{4chan/pol/358443862}) consumed=true
D/(15:56:12.659) KurobaEx | ReplyPresenter: processPostingStatusUpdates(TD{4chan/pol/358443862}) -> Attached
D/(15:56:12.660) KurobaEx | PostingService: mainNotificationUpdates() activeRepliesCount=0
D/(15:56:12.775) KurobaEx | Chan4CaptchaLayoutViewModel: requestCaptcha() requesting new captcha (forced: false, ttl: null, chanDescriptor=TD{4chan/pol/358443862})
D/(15:56:12.776) KurobaEx | viewModelInitialized: SuspendableInitializer awaitUntilInitialized() called when not initialized, awaiting...
D/(15:56:12.815) KurobaEx | ControllerNavigationManager: onControllerPresented(CaptchaContainerController)
D/(15:56:12.817) KurobaEx | viewModelInitialized: SuspendableInitializer initWithValue() called
D/(15:56:12.817) KurobaEx | viewModelInitialized: notifyAllWaiters throwable==null: true, waiters=0
D/(15:56:12.817) KurobaEx | viewModelInitialized: SuspendableInitializer initWithValue() done
D/(15:56:12.817) KurobaEx | viewModelInitialized: SuspendableInitializer awaitUntilInitialized() called when not initialized, done (diffTime=41ms)
D/(15:56:12.818) KurobaEx | Chan4CaptchaLayoutViewModel: requestCaptchaInternal(TD{4chan/pol/358443862}) requesting https://sys.4chan.org/captcha?board=pol&thread_id=358443862
D/(15:56:12.818) KurobaEx | Chan4: addChan4CookieHeader(), host=sys.4chan.org, captchaCookie=AQ_2JQj4F_uW<cut>mcw42oEJZB2u
D/(15:56:12.821) KurobaEx | suspendConvertIntoJsonObjectWithAdapter: url='https://sys.4chan.org/captcha?board=pol&thread_id=358443862'
D/(15:56:12.823) KurobaEx | CompositeDnsSelector: lookup okHttpUseDnsOverHttps: false
D/(15:56:12.823) KurobaEx | Dependency Injection: Using DnsSelector.Mode.IPV4_ONLY
D/(15:56:13.269) KurobaEx | Chan4CaptchaLayoutViewModel: requestCaptcha() success
D/(15:56:14.597) KurobaEx | ControllerNavigationManager: onControllerUnpresented(CaptchaContainerController)
D/(15:56:30.445) KurobaEx | ChanTicker: startOrRestartTickerInternal run action begin
D/(15:56:30.446) KurobaEx | ThreadPresenter: onChanTickerTick(TD{4chan/pol/358443862})
D/(15:56:30.446) KurobaEx | ThreadPresenter: normalLoad() start
D/(15:56:30.446) KurobaEx | ThreadPresenter: normalLoad(currentChanDescriptor=TD{4chan/pol/358443862}
D/(15:56:30.446) KurobaEx | ThreadPresenter: showLoading=false
D/(15:56:30.446) KurobaEx | ThreadPresenter: chanCacheUpdateOptions=UpdateCache
D/(15:56:30.446) KurobaEx | ThreadPresenter: chanLoadOptions=ChanLoadOptions(chanLoadOption=RetainAll)
D/(15:56:30.446) KurobaEx | ThreadPresenter: chanCacheOptions=ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache])
D/(15:56:30.446) KurobaEx | ThreadPresenter: chanReadOptions=ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647))
D/(15:56:30.446) KurobaEx | ChanTicker: startOrRestartTickerInternal run action end
D/(15:56:30.446) KurobaEx | ChanTicker: startOrRestartTickerInternal done, nextTimeoutIndex=1, nextWaitTimeSeconds=20
D/(15:56:30.449) KurobaEx | ChanThreadManager: loadThreadOrCatalog(null, null, TD{4chan/pol/358443862}, UpdateCache, ChanLoadOptions(chanLoadOption=RetainAll), ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache]), ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647))
D/(15:56:30.449) KurobaEx | ChanThreadManager: loadInternal() Requested thread /TD{4chan/pol/358443862}/
D/(15:56:30.449) KurobaEx | ThreadDataPreloadUseCase: preloadThreadInfo(TD{4chan/pol/358443862}) begin
D/(15:56:30.451) KurobaEx | ThreadLayout: handleLoadProgressEvent() Begin(chanDescriptor=TD{4chan/pol/358443862})
D/(15:56:30.455) KurobaEx | PostHideManager: chanPostHideRepository.preloadForThreadInternal() preloaded 0 post hides
D/(15:56:30.456) KurobaEx | ThreadDataPreloadUseCase: preloadThreadInfo(TD{4chan/pol/358443862}) end, took 6.832396ms
D/(15:56:30.456) KurobaEx | ChanThreadManager: loadInternal(), chanDescriptor=TD{4chan/pol/358443862} preloadThreadInfo took 7.179219ms
D/(15:56:30.456) KurobaEx | ChanThreadManager: loadInternal() chanThreadsCache.cacheNeedsUpdate(TD{4chan/pol/358443862}, UpdateCache) -> true
D/(15:56:30.457) KurobaEx | ChanThreadLoaderCoordinator: loadThreadOrCatalog(chanLoadUrl=ChanLoadUrl(url=https://a.4cdn.org/pol/thread/358443862.json, isIncremental=false, page=null), compositeCatalogDescriptor=null, chanDescriptor=TD{4chan/pol/358443862}, chanCacheOptions=ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache]), chanCacheUpdateOptions=UpdateCache, chanReadOptions=ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647), chanReader=FutabaChanReader, postProcessFlags=null)
D/(15:56:30.458) KurobaEx | ThreadLayout: handleLoadProgressEvent() Loading(chanDescriptor=TD{4chan/pol/358443862})
D/(15:56:30.980) KurobaEx | ThreadLayout: handleLoadProgressEvent() Reading(chanDescriptor=TD{4chan/pol/358443862})
D/(15:56:30.992) KurobaEx | ChanThreadLoaderCoordinator: loadThreadOrCatalog(chanLoadUrl='ChanLoadUrl(url=https://a.4cdn.org/pol/thread/358443862.json, isIncremental=false, page=null)') chanReaderProcessor=ChanReaderProcessor{chanDescriptor=TD{4chan/pol/358443862}, toParse=1, closed=false, deleted=false, archived=false, error=null}
D/(15:56:30.993) KurobaEx | NormalPostLoader: persistPosts(TD{4chan/pol/358443862}, ChanReaderProcessor{chanDescriptor=TD{4chan/pol/358443862}, toParse=1, closed=false, deleted=false, archived=false, error=null}, ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache]), UpdateCache, DefaultPostParser)
D/(15:56:30.995) KurobaEx | ParsePostsUseCase: parseNewPostsPosts(chanDescriptor=TD{4chan/pol/358443862}) -> parsedPosts=1
D/(15:56:30.995) KurobaEx | ParsePostsUseCase: parseNewPostsPosts(chanDescriptor=TD{4chan/pol/358443862}, postsToParseSize=1), internalIds=24, filters=0
D/(15:56:30.995) KurobaEx | ChanPostRepository: insertOrUpdateThreadPosts() 1 posts differ from the cache (total posts=1)
D/(15:56:30.998) KurobaEx | ChanThread: Thread cache (TD{4chan/pol/358443862}) Added 0 new posts, updated 1 posts, marked as deleted 0 posts. sortAndRecalculationDuration=26.145us
D/(15:56:30.998) KurobaEx | ChanPostRepository: insertOrUpdateMany(TD{4chan/pol/358443862}) -> 1
D/(15:56:31.001) KurobaEx | ThreadLayout: handleLoadProgressEvent() ParsingPosts(chanDescriptor=TD{4chan/pol/358443862}, postsToParseCount=1)
D/(15:56:31.001) KurobaEx | ThreadLayout: handleLoadProgressEvent() ProcessingFilters(chanDescriptor=TD{4chan/pol/358443862}, filtersCount=0)
D/(15:56:31.001) KurobaEx | ThreadLayout: handleLoadProgressEvent() PersistingPosts(chanDescriptor=TD{4chan/pol/358443862}, postsCount=1)
D/(15:56:31.008) KurobaEx | ChanThreadLoaderCoordinator: ChanReaderRequest.readJson() stats:
D/(15:56:31.008) KurobaEx | ChanThreadLoaderCoordinator: url = https://a.4cdn.org/pol/thread/358443862.json.
D/(15:56:31.008) KurobaEx | ChanThreadLoaderCoordinator: Network request execution took 521.263229ms.
D/(15:56:31.008) KurobaEx | ChanThreadLoaderCoordinator: Json reading took 12.334427ms.
D/(15:56:31.008) KurobaEx | ChanThreadLoaderCoordinator: Store new posts took 2.924323ms (stored 1 posts).
D/(15:56:31.008) KurobaEx | ChanThreadLoaderCoordinator: Parse posts took 522.292us (parsed 1 out of 24 posts).
D/(15:56:31.008) KurobaEx | ChanThreadLoaderCoordinator: Filter processing took 35.313us (filers count: 0).
D/(15:56:31.008) KurobaEx | ChanThreadLoaderCoordinator: Total in-memory cached posts count: 2419/13107.
D/(15:56:31.008) KurobaEx | ChanThreadLoaderCoordinator: Current thread cached posts count: 24
D/(15:56:31.008) KurobaEx | ChanThreadLoaderCoordinator: Threads with more than one post count: (24/8), total cached threads count: 487.
D/(15:56:31.008) KurobaEx | ChanThreadLoaderCoordinator: Total local processing time: 15.816355ms
D/(15:56:31.008) KurobaEx | ThreadDataPreloadUseCase: postloadThreadInfo(TD{4chan/pol/358443862}) begin
D/(15:56:31.008) KurobaEx | ThreadDataPreloadUseCase: postloadThreadInfo(TD{4chan/pol/358443862}) end
D/(15:56:31.008) KurobaEx | ChanThreadManager: loadThreadOrCatalog(), descriptor=TD{4chan/pol/358443862} postloadThreadInfo took 90.886us
D/(15:56:31.008) KurobaEx | ThreadPresenter: normalLoad() threadLoadResult=ThreadLoadResult.Loaded{chanDescriptor=TD{4chan/pol/358443862}} (currentChanDescriptor=TD{4chan/pol/358443862})
D/(15:56:31.008) KurobaEx | ThreadPresenter: onChanLoaderData() called, loadedChanDescriptor=TD{4chan/pol/358443862}
D/(15:56:31.008) KurobaEx | ChanTicker: kickTicker(false)
D/(15:56:31.009) KurobaEx | ChanTicker: StartOrResetTicker chanDescriptor=TD{4chan/pol/358443862}
D/(15:56:31.009) KurobaEx | ChanTicker: startOrRestartTickerInternal scheduled, chanDescriptor=TD{4chan/pol/358443862}, waiting 20000ms
D/(15:56:31.010) KurobaEx | PostsFilter: originalPosts.size=24, retainedPosts.size=24, chanDescriptor=TD{4chan/pol/358443862}
D/(15:56:31.010) KurobaEx | ThreadLayout: handleLoadProgressEvent() ApplyingFilters(chanDescriptor=TD{4chan/pol/358443862}, postHidesCount=0, postFiltersCount=0)
D/(15:56:31.011) KurobaEx | ThreadLayout: handleLoadProgressEvent() RefreshingPosts(chanDescriptor=TD{4chan/pol/358443862})
D/(15:56:31.011) KurobaEx | ThreadCellData: runPreloading() start
D/(15:56:31.011) KurobaEx | PostAdapter: setThread() notifyDataSetChanged called, postIndexedList.size=24
D/(15:56:31.011) KurobaEx | ThreadCellData: runPreloading() startingPosition=18, dataListSize=24
D/(15:56:31.011) KurobaEx | ThreadLayout: showPostsForChanDescriptor() showPosts(TD{4chan/pol/358443862}) -> true applyFilterDuration=239.323us, setThreadPostsDuration=1.311302ms, totalDuration=2.871875ms
D/(15:56:31.012) KurobaEx | ThreadPresenter: onChanLoaderData(TD{4chan/pol/358443862}) end, took 3.648906ms
D/(15:56:31.012) KurobaEx | ThreadPresenter: normalLoad() end
D/(15:56:31.012) KurobaEx | ThreadLayout: handleLoadProgressEvent() End(chanDescriptor=TD{4chan/pol/358443862})
D/(15:56:31.012) KurobaEx | HistoryNavigationManager: persistNavigationStack async called
D/(15:56:31.012) KurobaEx | HistoryNavigationManager: persistNavigationStackInternal navStackCopy.size=281
D/(15:56:31.014) KurobaEx | NavHistoryLocalSource: persist(navHistoryStack.size=281)
D/(15:56:31.024) KurobaEx | ThreadCellData: runPreloading() end, took 12.256927ms
D/(15:56:31.031) KurobaEx | HistoryNavigationRepository: persist(281) took 16.897656ms
D/(15:56:31.032) KurobaEx | HistoryNavigationManager: persistNavigationStack async finished
D/(15:56:51.010) KurobaEx | ChanTicker: startOrRestartTickerInternal run action begin
D/(15:56:51.010) KurobaEx | ThreadPresenter: onChanTickerTick(TD{4chan/pol/358443862})
D/(15:56:51.010) KurobaEx | ThreadPresenter: normalLoad() start
D/(15:56:51.010) KurobaEx | ThreadPresenter: normalLoad(currentChanDescriptor=TD{4chan/pol/358443862}
D/(15:56:51.010) KurobaEx | ThreadPresenter: showLoading=false
D/(15:56:51.010) KurobaEx | ThreadPresenter: chanCacheUpdateOptions=UpdateCache
D/(15:56:51.010) KurobaEx | ThreadPresenter: chanLoadOptions=ChanLoadOptions(chanLoadOption=RetainAll)
D/(15:56:51.010) KurobaEx | ThreadPresenter: chanCacheOptions=ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache])
D/(15:56:51.010) KurobaEx | ThreadPresenter: chanReadOptions=ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647))
D/(15:56:51.010) KurobaEx | ChanTicker: startOrRestartTickerInternal run action end
D/(15:56:51.010) KurobaEx | ChanTicker: startOrRestartTickerInternal done, nextTimeoutIndex=2, nextWaitTimeSeconds=30
D/(15:56:51.011) KurobaEx | ChanThreadManager: loadThreadOrCatalog(null, null, TD{4chan/pol/358443862}, UpdateCache, ChanLoadOptions(chanLoadOption=RetainAll), ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache]), ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647))
D/(15:56:51.011) KurobaEx | ChanThreadManager: loadInternal() Requested thread /TD{4chan/pol/358443862}/
D/(15:56:51.011) KurobaEx | ThreadDataPreloadUseCase: preloadThreadInfo(TD{4chan/pol/358443862}) begin
D/(15:56:51.011) KurobaEx | ThreadLayout: handleLoadProgressEvent() Begin(chanDescriptor=TD{4chan/pol/358443862})
D/(15:56:51.014) KurobaEx | PostHideManager: chanPostHideRepository.preloadForThreadInternal() preloaded 0 post hides
D/(15:56:51.014) KurobaEx | ThreadDataPreloadUseCase: preloadThreadInfo(TD{4chan/pol/358443862}) end, took 2.897917ms
D/(15:56:51.014) KurobaEx | ChanThreadManager: loadInternal(), chanDescriptor=TD{4chan/pol/358443862} preloadThreadInfo took 3.021511ms
D/(15:56:51.014) KurobaEx | ChanThreadManager: loadInternal() chanThreadsCache.cacheNeedsUpdate(TD{4chan/pol/358443862}, UpdateCache) -> true
D/(15:56:51.014) KurobaEx | ChanThreadLoaderCoordinator: loadThreadOrCatalog(chanLoadUrl=ChanLoadUrl(url=https://a.4cdn.org/pol/thread/358443862.json, isIncremental=false, page=null), compositeCatalogDescriptor=null, chanDescriptor=TD{4chan/pol/358443862}, chanCacheOptions=ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache]), chanCacheUpdateOptions=UpdateCache, chanReadOptions=ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647), chanReader=FutabaChanReader, postProcessFlags=null)
D/(15:56:51.014) KurobaEx | ThreadLayout: handleLoadProgressEvent() Loading(chanDescriptor=TD{4chan/pol/358443862})
D/(15:56:51.251) KurobaEx | ChanThreadLoaderCoordinator: loadThreadOrCatalog(chanLoadUrl='ChanLoadUrl(url=https://a.4cdn.org/pol/thread/358443862.json, isIncremental=false, page=null)') chanReaderProcessor=ChanReaderProcessor{chanDescriptor=TD{4chan/pol/358443862}, toParse=1, closed=false, deleted=false, archived=false, error=null}
D/(15:56:51.251) KurobaEx | NormalPostLoader: persistPosts(TD{4chan/pol/358443862}, ChanReaderProcessor{chanDescriptor=TD{4chan/pol/358443862}, toParse=1, closed=false, deleted=false, archived=false, error=null}, ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache]), UpdateCache, DefaultPostParser)
D/(15:56:51.252) KurobaEx | ThreadLayout: handleLoadProgressEvent() Reading(chanDescriptor=TD{4chan/pol/358443862})
D/(15:56:51.254) KurobaEx | ThreadLayout: handleLoadProgressEvent() ParsingPosts(chanDescriptor=TD{4chan/pol/358443862}, postsToParseCount=1)
D/(15:56:51.254) KurobaEx | ParsePostsUseCase: parseNewPostsPosts(chanDescriptor=TD{4chan/pol/358443862}) -> parsedPosts=1
D/(15:56:51.255) KurobaEx | ThreadLayout: handleLoadProgressEvent() ProcessingFilters(chanDescriptor=TD{4chan/pol/358443862}, filtersCount=0)
D/(15:56:51.255) KurobaEx | ParsePostsUseCase: parseNewPostsPosts(chanDescriptor=TD{4chan/pol/358443862}, postsToParseSize=1), internalIds=24, filters=0
D/(15:56:51.255) KurobaEx | ThreadLayout: handleLoadProgressEvent() PersistingPosts(chanDescriptor=TD{4chan/pol/358443862}, postsCount=1)
D/(15:56:51.255) KurobaEx | ChanPostRepository: insertOrUpdateThreadPosts() 1 posts differ from the cache (total posts=1)
D/(15:56:51.256) KurobaEx | ChanThread: Thread cache (TD{4chan/pol/358443862}) Added 0 new posts, updated 1 posts, marked as deleted 0 posts. sortAndRecalculationDuration=12.969us
D/(15:56:51.256) KurobaEx | ChanPostRepository: insertOrUpdateMany(TD{4chan/pol/358443862}) -> 1
D/(15:56:51.259) KurobaEx | ChanThreadLoaderCoordinator: ChanReaderRequest.readJson() stats:
D/(15:56:51.259) KurobaEx | ChanThreadLoaderCoordinator: url = https://a.4cdn.org/pol/thread/358443862.json.
D/(15:56:51.259) KurobaEx | ChanThreadLoaderCoordinator: Network request execution took 231.960781ms.
D/(15:56:51.259) KurobaEx | ChanThreadLoaderCoordinator: Json reading took 4.382136ms.
D/(15:56:51.259) KurobaEx | ChanThreadLoaderCoordinator: Store new posts took 1.344063ms (stored 1 posts).
D/(15:56:51.259) KurobaEx | ChanThreadLoaderCoordinator: Parse posts took 305.625us (parsed 1 out of 24 posts).
D/(15:56:51.259) KurobaEx | ChanThreadLoaderCoordinator: Filter processing took 16.771us (filers count: 0).
D/(15:56:51.259) KurobaEx | ChanThreadLoaderCoordinator: Total in-memory cached posts count: 2419/13107.
D/(15:56:51.259) KurobaEx | ChanThreadLoaderCoordinator: Current thread cached posts count: 24
D/(15:56:51.259) KurobaEx | ChanThreadLoaderCoordinator: Threads with more than one post count: (24/8), total cached threads count: 487.
D/(15:56:51.259) KurobaEx | ChanThreadLoaderCoordinator: Total local processing time: 6.048595ms
D/(15:56:51.259) KurobaEx | ThreadDataPreloadUseCase: postloadThreadInfo(TD{4chan/pol/358443862}) begin
D/(15:56:51.259) KurobaEx | ThreadDataPreloadUseCase: postloadThreadInfo(TD{4chan/pol/358443862}) end
D/(15:56:51.259) KurobaEx | ChanThreadManager: loadThreadOrCatalog(), descriptor=TD{4chan/pol/358443862} postloadThreadInfo took 61.302us
D/(15:56:51.259) KurobaEx | ThreadPresenter: normalLoad() threadLoadResult=ThreadLoadResult.Loaded{chanDescriptor=TD{4chan/pol/358443862}} (currentChanDescriptor=TD{4chan/pol/358443862})
D/(15:56:51.259) KurobaEx | ThreadPresenter: onChanLoaderData() called, loadedChanDescriptor=TD{4chan/pol/358443862}
D/(15:56:51.260) KurobaEx | ChanTicker: kickTicker(false)
D/(15:56:51.260) KurobaEx | ChanTicker: StartOrResetTicker chanDescriptor=TD{4chan/pol/358443862}
D/(15:56:51.260) KurobaEx | ChanTicker: startOrRestartTickerInternal scheduled, chanDescriptor=TD{4chan/pol/358443862}, waiting 30000ms
D/(15:56:51.261) KurobaEx | PostsFilter: originalPosts.size=24, retainedPosts.size=24, chanDescriptor=TD{4chan/pol/358443862}
D/(15:56:51.261) KurobaEx | ThreadLayout: handleLoadProgressEvent() ApplyingFilters(chanDescriptor=TD{4chan/pol/358443862}, postHidesCount=0, postFiltersCount=0)
D/(15:56:51.261) KurobaEx | ThreadLayout: handleLoadProgressEvent() RefreshingPosts(chanDescriptor=TD{4chan/pol/358443862})
D/(15:56:51.262) KurobaEx | PostAdapter: setThread() notifyDataSetChanged called, postIndexedList.size=24
D/(15:56:51.262) KurobaEx | ThreadCellData: runPreloading() start
D/(15:56:51.262) KurobaEx | ThreadLayout: showPostsForChanDescriptor() showPosts(TD{4chan/pol/358443862}) -> true applyFilterDuration=151.198us, setThreadPostsDuration=1.248333ms, totalDuration=2.329896ms
D/(15:56:51.262) KurobaEx | ThreadCellData: runPreloading() startingPosition=18, dataListSize=24
D/(15:56:51.263) KurobaEx | ThreadPresenter: onChanLoaderData(TD{4chan/pol/358443862}) end, took 3.040417ms
D/(15:56:51.263) KurobaEx | ThreadPresenter: normalLoad() end
D/(15:56:51.263) KurobaEx | ThreadLayout: handleLoadProgressEvent() End(chanDescriptor=TD{4chan/pol/358443862})
D/(15:56:51.263) KurobaEx | HistoryNavigationManager: persistNavigationStack async called
D/(15:56:51.263) KurobaEx | HistoryNavigationManager: persistNavigationStackInternal navStackCopy.size=281
D/(15:56:51.263) KurobaEx | NavHistoryLocalSource: persist(navHistoryStack.size=281)
D/(15:56:51.271) KurobaEx | ThreadCellData: runPreloading() end, took 9.117552ms
D/(15:56:51.278) KurobaEx | HistoryNavigationRepository: persist(281) took 14.116980ms
D/(15:56:51.278) KurobaEx | HistoryNavigationManager: persistNavigationStack async finished
E/(15:56:54.763) KurobaEx | Chan: Unhandled exception in thread: main
E/(15:56:54.763) KurobaEx | Chan: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 295892 bytes
E/(15:56:54.763) KurobaEx | Chan: 	at android.view.autofill.AutofillManager.updateSessionLocked(AutofillManager.java:1975)
E/(15:56:54.763) KurobaEx | Chan: 	at android.view.autofill.AutofillManager.notifyViewEnteredLocked(AutofillManager.java:1098)
E/(15:56:54.763) KurobaEx | Chan: 	at android.view.autofill.AutofillManager.notifyViewEntered(AutofillManager.java:1048)
E/(15:56:54.763) KurobaEx | Chan: 	at android.view.autofill.AutofillManager.notifyViewEntered(AutofillManager.java:1005)
E/(15:56:54.763) KurobaEx | Chan: 	at android.view.View.notifyEnterOrExitForAutoFillIfNeeded(View.java:8501)
E/(15:56:54.763) KurobaEx | Chan: 	at android.view.View.performClick(View.java:7800)
E/(15:56:54.763) KurobaEx | Chan: 	at android.widget.TextView.performClick(TextView.java:16041)
E/(15:56:54.763) KurobaEx | Chan: 	at android.view.View.performClickInternal(View.java:7769)
E/(15:56:54.763) KurobaEx | Chan: 	at android.view.View.access$3800(View.java:910)
E/(15:56:54.763) KurobaEx | Chan: 	at android.view.View$PerformClick.run(View.java:30184)
E/(15:56:54.763) KurobaEx | Chan: 	at android.os.Handler.handleCallback(Handler.java:938)
E/(15:56:54.763) KurobaEx | Chan: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/(15:56:54.763) KurobaEx | Chan: 	at android.os.Looper.loopOnce(Looper.java:226)
E/(15:56:54.763) KurobaEx | Chan: 	at android.os.Looper.loop(Looper.java:313)
E/(15:56:54.763) KurobaEx | Chan: 	at android.app.ActivityThread.main(ActivityThread.java:8582)
E/(15:56:54.763) KurobaEx | Chan: 	at java.lang.reflect.Method.invoke(Native Method)
E/(15:56:54.763) KurobaEx | Chan: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:563)
E/(15:56:54.763) KurobaEx | Chan: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
E/(15:56:54.763) KurobaEx | Chan: Caused by: android.os.TransactionTooLargeException: data parcel size 295892 bytes
E/(15:56:54.763) KurobaEx | Chan: 	at android.os.BinderProxy.transactNative(Native Method)
E/(15:56:54.763) KurobaEx | Chan: 	at android.os.BinderProxy.transact(BinderProxy.java:635)
E/(15:56:54.763) KurobaEx | Chan: 	at android.view.autofill.IAutoFillManager$Stub$Proxy.updateSession(IAutoFillManager.java:737)
E/(15:56:54.763) KurobaEx | Chan: 	at android.view.autofill.AutofillManager.updateSessionLocked(AutofillManager.java:1972)
E/(15:56:54.763) KurobaEx | Chan: 	... 17 more


------------------------------
Android API Level: 31
App Version: v1.3.4
Phone Model: samsung SM-G998U
Build type: Release
Flavor type: Stable
isLowRamDevice: false, isLowRamDeviceForced: false
MemoryClass: 256
App running time: 09:30:47.675
------------------------------
Current layout mode: PHONE
Board view mode: GRID
Bottom navigation enabled: true
Prefetching enabled: false
Hi-res thumbnails enabled: false
mediaViewerMaxOffscreenPages: 2
CloudFlare force preload enabled: false
useMpvVideoPlayer: true
userAgent: Mozilla/5.0 (Linux; Android 12; SM-G998U Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/97.0.4692.98 Mobile Safari/537.36
kurobaExCustomUserAgent: KurobaEx v1.3.4
maxPostsCountInPostsCache: 13107
maxAmountOfPostsInDatabase: 75000
maxAmountOfThreadsInDatabase: 12500
diskCacheSizeMegabytes: 256
prefetchDiskCacheSizeMegabytes: 512
diskCacheCleanupRemovePercent: 25
ImageSaver root directory: content://com.android.externalstorage.documents/tree/primary%3AKurobaex
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
Foreground watcher enabled: false
Background watcher enabled: false
Filter watch enabled: false
Thread downloader interval: 3600000
Thread downloader download media on metered network: false
------------------------------
```

**Comment by K1rakishou** [comment] 2022-01-27 22:53
Duplicate of https://github.com/KurobaExReports/Reports/issues/58

**Closed by K1rakishou** 2022-01-27 22:53 UTC
Labels: New, Crash
