### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#178] opened 2022-02-28 07:40 UTC
```=== LOGS(2022-02-28 07:40:11 UTC) ===
D/(23:40:04.886) KurobaEx-fdroid | ChanTicker: startOrRestartTickerInternal run action begin
D/(23:40:04.886) KurobaEx-fdroid | ThreadPresenter: onChanTickerTick(TD{4chan/v/590280628})
D/(23:40:04.886) KurobaEx-fdroid | ThreadPresenter: normalLoad() start
D/(23:40:04.886) KurobaEx-fdroid | ThreadPresenter: normalLoad(currentChanDescriptor=TD{4chan/v/590280628}
D/(23:40:04.886) KurobaEx-fdroid | ThreadPresenter: showLoading=false
D/(23:40:04.886) KurobaEx-fdroid | ThreadPresenter: chanCacheUpdateOptions=UpdateCache
D/(23:40:04.886) KurobaEx-fdroid | ThreadPresenter: chanLoadOptions=ChanLoadOptions(chanLoadOption=RetainAll)
D/(23:40:04.886) KurobaEx-fdroid | ThreadPresenter: chanCacheOptions=ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache])
D/(23:40:04.886) KurobaEx-fdroid | ThreadPresenter: chanReadOptions=ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647))
D/(23:40:04.886) KurobaEx-fdroid | ChanTicker: startOrRestartTickerInternal run action end
D/(23:40:04.886) KurobaEx-fdroid | ChanTicker: startOrRestartTickerInternal done, nextTimeoutIndex=4, nextWaitTimeSeconds=60
D/(23:40:04.886) KurobaEx-fdroid | ChanThreadManager: loadThreadOrCatalog(null, null, TD{4chan/v/590280628}, UpdateCache, ChanLoadOptions(chanLoadOption=RetainAll), ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache]), ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647))
D/(23:40:04.886) KurobaEx-fdroid | ChanThreadManager: loadInternal() Requested thread /TD{4chan/v/590280628}/
D/(23:40:04.886) KurobaEx-fdroid | ThreadDataPreloadUseCase: preloadThreadInfo(TD{4chan/v/590280628}) begin
D/(23:40:04.887) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() Begin(chanDescriptor=TD{4chan/v/590280628})
D/(23:40:04.888) KurobaEx-fdroid | PostHideManager: chanPostHideRepository.preloadForThreadInternal() preloaded 0 post hides
D/(23:40:04.888) KurobaEx-fdroid | ThreadDataPreloadUseCase: preloadThreadInfo(TD{4chan/v/590280628}) end, took 1.714740ms
D/(23:40:04.888) KurobaEx-fdroid | ChanThreadManager: loadInternal(), chanDescriptor=TD{4chan/v/590280628} preloadThreadInfo took 1.813958ms
D/(23:40:04.888) KurobaEx-fdroid | ChanThreadManager: loadInternal() chanThreadsCache.cacheNeedsUpdate(TD{4chan/v/590280628}, UpdateCache) -> true
D/(23:40:04.888) KurobaEx-fdroid | ChanThreadLoaderCoordinator: loadThreadOrCatalog(chanLoadUrl=ChanLoadUrl(url=https://a.4cdn.org/v/thread/590280628.json, isIncremental=false, page=null), compositeCatalogDescriptor=null, chanDescriptor=TD{4chan/v/590280628}, chanCacheOptions=ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache]), chanCacheUpdateOptions=UpdateCache, chanReadOptions=ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647), chanReader=FutabaChanReader, postProcessFlags=null)
D/(23:40:04.889) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() Loading(chanDescriptor=TD{4chan/v/590280628})
D/(23:40:04.935) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() Reading(chanDescriptor=TD{4chan/v/590280628})
D/(23:40:04.953) KurobaEx-fdroid | ChanThreadLoaderCoordinator: loadThreadOrCatalog(chanLoadUrl='ChanLoadUrl(url=https://a.4cdn.org/v/thread/590280628.json, isIncremental=false, page=null)') chanReaderProcessor=ChanReaderProcessor{chanDescriptor=TD{4chan/v/590280628}, toParse=1, closed=false, deleted=false, archived=false, error=null}
D/(23:40:04.954) KurobaEx-fdroid | NormalPostLoader: persistPosts(TD{4chan/v/590280628}, ChanReaderProcessor{chanDescriptor=TD{4chan/v/590280628}, toParse=1, closed=false, deleted=false, archived=false, error=null}, ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache]), UpdateCache, DefaultPostParser)
D/(23:40:04.954) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() ParsingPosts(chanDescriptor=TD{4chan/v/590280628}, postsToParseCount=1)
D/(23:40:04.954) KurobaEx-fdroid | ParsePostsUseCase: parseNewPostsPosts(chanDescriptor=TD{4chan/v/590280628}) -> parsedPosts=1
D/(23:40:04.954) KurobaEx-fdroid | ParsePostsUseCase: parseNewPostsPosts(chanDescriptor=TD{4chan/v/590280628}, postsToParseSize=1), internalIds=452, filters=0
D/(23:40:04.954) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() ProcessingFilters(chanDescriptor=TD{4chan/v/590280628}, filtersCount=0)
D/(23:40:04.954) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() PersistingPosts(chanDescriptor=TD{4chan/v/590280628}, postsCount=1)
D/(23:40:04.954) KurobaEx-fdroid | ChanPostRepository: insertOrUpdateThreadPosts() 1 posts differ from the cache (total posts=1)
D/(23:40:04.955) KurobaEx-fdroid | ChanThread: Thread cache (TD{4chan/v/590280628}) Added 0 new posts, updated 1 posts, marked as deleted 0 posts. sortAndRecalculationDuration=74.479us
D/(23:40:04.955) KurobaEx-fdroid | ChanPostRepository: insertOrUpdateMany(TD{4chan/v/590280628}) -> 1
D/(23:40:04.956) KurobaEx-fdroid | ChanThreadLoaderCoordinator: ChanReaderRequest.readJson() stats:
D/(23:40:04.956) KurobaEx-fdroid | ChanThreadLoaderCoordinator: url = https://a.4cdn.org/v/thread/590280628.json.
D/(23:40:04.956) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Network request execution took 44.988229ms.
D/(23:40:04.956) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Json reading took 19.751979ms.
D/(23:40:04.956) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Store new posts took 631.927us (stored 1 posts).
D/(23:40:04.956) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Parse posts took 115.937us (parsed 1 out of 452 posts).
D/(23:40:04.956) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Filter processing took 938ns (filers count: 0).
D/(23:40:04.956) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Total in-memory cached posts count: 3187/13107.
D/(23:40:04.956) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Current thread cached posts count: 452
D/(23:40:04.956) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Threads with more than one post count: (12/8), total cached threads count: 399.
D/(23:40:04.956) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Total local processing time: 20.500781ms
D/(23:40:04.956) KurobaEx-fdroid | ThreadDataPreloadUseCase: postloadThreadInfo(TD{4chan/v/590280628}) begin
D/(23:40:04.956) KurobaEx-fdroid | ThreadDataPreloadUseCase: postloadThreadInfo(TD{4chan/v/590280628}) end
D/(23:40:04.956) KurobaEx-fdroid | ChanThreadManager: loadThreadOrCatalog(), descriptor=TD{4chan/v/590280628} postloadThreadInfo took 51.979us
D/(23:40:04.956) KurobaEx-fdroid | ThreadPresenter: normalLoad() threadLoadResult=ThreadLoadResult.Loaded{chanDescriptor=TD{4chan/v/590280628}} (currentChanDescriptor=TD{4chan/v/590280628})
D/(23:40:04.956) KurobaEx-fdroid | ThreadPresenter: onChanLoaderData() called, loadedChanDescriptor=TD{4chan/v/590280628}
D/(23:40:04.956) KurobaEx-fdroid | ChanTicker: kickTicker(false)
D/(23:40:04.956) KurobaEx-fdroid | ChanTicker: StartOrResetTicker chanDescriptor=TD{4chan/v/590280628}
D/(23:40:04.956) KurobaEx-fdroid | ChanTicker: startOrRestartTickerInternal scheduled, chanDescriptor=TD{4chan/v/590280628}, waiting 60000ms
D/(23:40:04.957) KurobaEx-fdroid | PostsFilter: originalPosts.size=452, retainedPosts.size=452, chanDescriptor=TD{4chan/v/590280628}
D/(23:40:04.957) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() ApplyingFilters(chanDescriptor=TD{4chan/v/590280628}, postHidesCount=0, postFiltersCount=0)
D/(23:40:04.957) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() RefreshingPosts(chanDescriptor=TD{4chan/v/590280628})
D/(23:40:04.957) KurobaEx-fdroid | ThreadCellData: runPreloading() start
D/(23:40:04.957) KurobaEx-fdroid | ThreadCellData: runPreloading() startingPosition=0, dataListSize=452
D/(23:40:04.957) KurobaEx-fdroid | PostAdapter: setThread() notifyDataSetChanged called, postIndexedList.size=452
D/(23:40:04.958) KurobaEx-fdroid | ThreadLayout: showPostsForChanDescriptor() showPosts(TD{4chan/v/590280628}) -> true applyFilterDuration=462.604us, setThreadPostsDuration=516.771us, totalDuration=1.372708ms
D/(23:40:04.958) KurobaEx-fdroid | ThreadPresenter: onChanLoaderData(TD{4chan/v/590280628}) end, took 2.338959ms
D/(23:40:04.958) KurobaEx-fdroid | ThreadPresenter: normalLoad() end
D/(23:40:04.959) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() End(chanDescriptor=TD{4chan/v/590280628})
D/(23:40:04.996) KurobaEx-fdroid | ThreadCellData: runPreloading() end, took 38.711146ms
E/(23:40:10.770) KurobaEx-fdroid | Chan: Unhandled exception in thread: main
E/(23:40:10.770) KurobaEx-fdroid | Chan: DeadSystemException: The system died; earlier logs will point to the root cause


=== STACKTRACE ===
Called from unhandled exception handler.
java.lang.RuntimeException: android.os.DeadSystemException
	at android.view.autofill.AutofillManager.updateSessionLocked(AutofillManager.java:1975)
	at android.view.autofill.AutofillManager.notifyValueChanged(AutofillManager.java:1377)
	at android.widget.TextView.notifyListeningManagersAfterTextChanged(TextView.java:11910)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:11890)
	at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:15166)
	at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1288)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:588)
	at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:11)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:518)
	at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:2)
	at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:945)
	at android.view.inputmethod.BaseInputConnection.setComposingText(BaseInputConnection.java:712)
	at android.view.inputmethod.InputConnectionWrapper.setComposingText(InputConnectionWrapper.java:165)
	at android.view.inputmethod.InputConnectionWrapper.setComposingText(InputConnectionWrapper.java:165)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:650)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:118)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8641)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
Caused by: android.os.DeadSystemException
	... 23 more


------------------------------
Android API Level: 31
App Version: v1.3.4
Phone Model: samsung SM-G781U
Build type: Unknown
Flavor type: Fdroid
isLowRamDevice: false, isLowRamDeviceForced: false
MemoryClass: 256
App running time: 12:00:54.420
------------------------------
Current layout mode: SLIDE
Board view mode: GRID
Bottom navigation enabled: true
Prefetching enabled: false
Hi-res thumbnails enabled: true
mediaViewerMaxOffscreenPages: 2
CloudFlare force preload enabled: false
useMpvVideoPlayer: false
userAgent: Mozilla/5.0 (Linux; Android 12; SM-G781U Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/98.0.4758.101 Mobile Safari/537.36
kurobaExCustomUserAgent: KurobaEx-fdroid v1.3.4
maxPostsCountInPostsCache: 13107
maxAmountOfPostsInDatabase: 75000
maxAmountOfThreadsInDatabase: 12500
diskCacheSizeMegabytes: 256
prefetchDiskCacheSizeMegabytes: 512
diskCacheCleanupRemovePercent: 25
ImageSaver root directory: content://com.android.externalstorage.documents/tree/primary%3AClover
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
Foreground watcher enabled: true
Watch foreground interval: 30000
Watch foreground adaptive interval: false
Background watcher enabled: false
Filter watch enabled: false
Thread downloader interval: 3600000
Thread downloader download media on metered network: false
------------------------------
```

**Comment by K1rakishou** [comment] 2022-03-03 08:14
Duplicate of https://github.com/KurobaExReports/Reports/issues/172

**Closed by K1rakishou** 2022-03-03 08:14 UTC
Labels: Crash
