### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#96] opened 2022-02-07 04:39 UTC
```=== LOGS(2022-02-07 04:05:10 UTC) ===


=== STACKTRACE ===
Called from unhandled exception handler.
java.lang.IllegalArgumentException: Bad postCellDataWidthNoPaddings: 0
	at com.github.k1rakishou.chan.ui.cell.ThreadCellData.updateThreadData(ThreadCellData.kt:35)
	at com.github.k1rakishou.chan.ui.adapter.PostRepliesAdapter.setOrUpdateData(PostRepliesAdapter.kt:9)
	at com.github.k1rakishou.chan.ui.controller.popup.PostRepliesPopupController$displayData$2.invokeSuspend(PostRepliesPopupController.kt:59)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:5)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8163)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)


------------------------------
Android API Level: 30
App Version: v1.3.5
Phone Model: Xiaomi 2201117TG
Build type: Release
Flavor type: Beta
isLowRamDevice: false, isLowRamDeviceForced: false
MemoryClass: 256
App running time: 00:27:53.766
------------------------------
Current layout mode: SLIDE
Board view mode: LIST
Bottom navigation enabled: true
Prefetching enabled: true
Hi-res thumbnails enabled: true
mediaViewerMaxOffscreenPages: 1
CloudFlare force preload enabled: false
useMpvVideoPlayer: false
userAgent: Mozilla/5.0 (Linux; Android 11; 2201117TG Build/RKQ1.211001.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/98.0.4758.87 Mobile Safari/537.36
kurobaExCustomUserAgent: KurobaEx-beta v1.3.5
maxPostsCountInPostsCache: 13107
maxAmountOfPostsInDatabase: 75000
maxAmountOfThreadsInDatabase: 12500
diskCacheSizeMegabytes: 256
prefetchDiskCacheSizeMegabytes: 512
diskCacheCleanupRemovePercent: 25
ImageSaver root directory: content://com.android.externalstorage.documents/tree/primary%3APictures%2FKuroba
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
Foreground watcher enabled: true
Watch foreground interval: 30000
Watch foreground adaptive interval: true
Background watcher enabled: true
Watch background interval: 300000
Filter watch enabled: true
Filter watch interval: 43200000
Thread downloader interval: 3600000
Thread downloader download media on metered network: false
------------------------------
```

**Comment by K1rakishou** [comment] 2022-02-12 10:02
Duplicate of https://github.com/KurobaExReports/Reports/issues/61

**Closed by K1rakishou** 2022-02-12 10:02 UTC
Labels: New, Crash
