### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by KurobaExReports** [KurobaExReports/Reports#175] opened 2022-02-27 11:15 UTC
```=== LOGS(2022-02-26 21:18:06 UTC) ===
D/(16:16:49.339) KurobaEx-fdroid | BookmarkWatcherCoordinator: restartBackgroundWork() called tag=BookmarkWatcherController_Fdroid
D/(16:16:49.339) KurobaEx-fdroid | BookmarkWatcherCoordinator: restartBackgroundWork() cannot restart watcher because one of the required settings is turned off (watchEnabled=true, watchBackground=false)
D/(16:16:49.339) KurobaEx-fdroid | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() called tag=BookmarkWatcherController_Fdroid
D/(16:16:49.341) KurobaEx-fdroid | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() work with tag BookmarkWatcherController_Fdroid canceled
D/(16:16:49.341) KurobaEx-fdroid | BookmarkWatcherDelegate: awaitUntilAllDependenciesAreReady()...
D/(16:16:49.341) KurobaEx-fdroid | BookmarkWatcherDelegate: awaitUntilAllDependenciesAreReady()...done
D/(16:16:49.341) KurobaEx-fdroid | BookmarkWatcherDelegate: doWorkInternal() updating 5 bookmarks
D/(16:16:49.341) KurobaEx-fdroid | LastPageNotificationsHelper: showOrUpdateNotifications(5)
D/(16:16:49.341) KurobaEx-fdroid | LastPageNotificationsHelper: ChanSettings.watchLastPageNotify is disabled
D/(16:16:49.341) KurobaEx-fdroid | BookmarkWatcherDelegate: BookmarkWatcherDelegate.doWork() called, isCalledFromForeground=true, currentThreadDescriptor=TD{4chan/v/590201574}
D/(16:16:49.341) KurobaEx-fdroid | FetchThreadBookmarkInfoUseCase: FetchThreadBookmarkInfoUseCase.execute(5)
D/(16:16:49.555) KurobaEx-fdroid | BookmarkWatcherDelegate: fetchThreadBookmarkInfo stats: total results=5, errorsCount=0, alreadyDeletedCount=0, notFoundOnServerCount=0, badStatusCount=0, successCount=5
D/(16:16:49.579) KurobaEx-fdroid | BookmarkWatcherDelegate: BookmarkWatcherDelegate.doWork() success, activeBookmarksCount=5
D/(16:16:49.580) KurobaEx-fdroid | BookmarkWatcherDelegate: BookmarkWatcherDelegate.doWork() took 238.25ms
D/(16:16:50.581) KurobaEx-fdroid | ReplyNotificationsHelper: showOrUpdateNotificationsInternal() ChanSettings.replyNotifications == false
D/(16:17:20.163) KurobaEx-fdroid | ChanTicker: startOrRestartTickerInternal run action begin
D/(16:17:20.163) KurobaEx-fdroid | ThreadPresenter: onChanTickerTick(TD{4chan/v/590201574})
D/(16:17:20.163) KurobaEx-fdroid | ThreadPresenter: normalLoad() start
D/(16:17:20.163) KurobaEx-fdroid | ThreadPresenter: normalLoad(currentChanDescriptor=TD{4chan/v/590201574}
D/(16:17:20.163) KurobaEx-fdroid | ThreadPresenter: showLoading=false
D/(16:17:20.163) KurobaEx-fdroid | ThreadPresenter: chanCacheUpdateOptions=UpdateCache
D/(16:17:20.163) KurobaEx-fdroid | ThreadPresenter: chanLoadOptions=ChanLoadOptions(chanLoadOption=RetainAll)
D/(16:17:20.163) KurobaEx-fdroid | ThreadPresenter: chanCacheOptions=ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache])
D/(16:17:20.163) KurobaEx-fdroid | ThreadPresenter: chanReadOptions=ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647))
D/(16:17:20.163) KurobaEx-fdroid | ChanTicker: startOrRestartTickerInternal run action end
D/(16:17:20.163) KurobaEx-fdroid | ChanTicker: startOrRestartTickerInternal done, nextTimeoutIndex=4, nextWaitTimeSeconds=60
D/(16:17:20.163) KurobaEx-fdroid | ChanThreadManager: loadThreadOrCatalog(null, null, TD{4chan/v/590201574}, UpdateCache, ChanLoadOptions(chanLoadOption=RetainAll), ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache]), ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647))
D/(16:17:20.163) KurobaEx-fdroid | ChanThreadManager: loadInternal() Requested thread /TD{4chan/v/590201574}/
D/(16:17:20.163) KurobaEx-fdroid | ThreadDataPreloadUseCase: preloadThreadInfo(TD{4chan/v/590201574}) begin
D/(16:17:20.164) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() Begin(chanDescriptor=TD{4chan/v/590201574})
D/(16:17:20.168) KurobaEx-fdroid | ThreadDataPreloadUseCase: preloadThreadInfo(TD{4chan/v/590201574}) end, took 4.358698ms
D/(16:17:20.168) KurobaEx-fdroid | ChanThreadManager: loadInternal(), chanDescriptor=TD{4chan/v/590201574} preloadThreadInfo took 4.574948ms
D/(16:17:20.168) KurobaEx-fdroid | ChanThreadManager: loadInternal() chanThreadsCache.cacheNeedsUpdate(TD{4chan/v/590201574}, UpdateCache) -> true
D/(16:17:20.169) KurobaEx-fdroid | ChanThreadLoaderCoordinator: loadThreadOrCatalog(chanLoadUrl=ChanLoadUrl(url=https://a.4cdn.org/v/thread/590201574.json, isIncremental=false, page=null), compositeCatalogDescriptor=null, chanDescriptor=TD{4chan/v/590201574}, chanCacheOptions=ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache]), chanCacheUpdateOptions=UpdateCache, chanReadOptions=ChanReadOptions(readOriginalPost=true, readFirstPostsCount=2147483647, readLastPostsCount=2147483647), chanReader=FutabaChanReader, postProcessFlags=null)
D/(16:17:20.170) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() Loading(chanDescriptor=TD{4chan/v/590201574})
D/(16:17:20.280) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() Reading(chanDescriptor=TD{4chan/v/590201574})
D/(16:17:20.283) KurobaEx-fdroid | ChanThreadLoaderCoordinator: loadThreadOrCatalog(chanLoadUrl='ChanLoadUrl(url=https://a.4cdn.org/v/thread/590201574.json, isIncremental=false, page=null)') chanReaderProcessor=ChanReaderProcessor{chanDescriptor=TD{4chan/v/590201574}, toParse=1, closed=false, deleted=false, archived=false, error=null}
D/(16:17:20.284) KurobaEx-fdroid | NormalPostLoader: persistPosts(TD{4chan/v/590201574}, ChanReaderProcessor{chanDescriptor=TD{4chan/v/590201574}, toParse=1, closed=false, deleted=false, archived=false, error=null}, ChanCacheOptions(options=[StoreInMemory, CanAddInFrontOfTheMemoryCache]), UpdateCache, DefaultPostParser)
D/(16:17:20.285) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() ParsingPosts(chanDescriptor=TD{4chan/v/590201574}, postsToParseCount=1)
D/(16:17:20.285) KurobaEx-fdroid | ParsePostsUseCase: parseNewPostsPosts(chanDescriptor=TD{4chan/v/590201574}) -> parsedPosts=1
D/(16:17:20.286) KurobaEx-fdroid | ParsePostsUseCase: parseNewPostsPosts(chanDescriptor=TD{4chan/v/590201574}, postsToParseSize=1), internalIds=38, filters=0
D/(16:17:20.286) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() ProcessingFilters(chanDescriptor=TD{4chan/v/590201574}, filtersCount=0)
D/(16:17:20.286) KurobaEx-fdroid | ChanPostRepository: insertOrUpdateThreadPosts() 1 posts differ from the cache (total posts=1)
D/(16:17:20.286) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() PersistingPosts(chanDescriptor=TD{4chan/v/590201574}, postsCount=1)
D/(16:17:20.286) KurobaEx-fdroid | ChanThread: Thread cache (TD{4chan/v/590201574}) Added 0 new posts, updated 1 posts, marked as deleted 0 posts. sortAndRecalculationDuration=25.104us
D/(16:17:20.286) KurobaEx-fdroid | ChanPostRepository: insertOrUpdateMany(TD{4chan/v/590201574}) -> 1
D/(16:17:20.295) KurobaEx-fdroid | ChanThreadLoaderCoordinator: ChanReaderRequest.readJson() stats:
D/(16:17:20.295) KurobaEx-fdroid | ChanThreadLoaderCoordinator: url = https://a.4cdn.org/v/thread/590201574.json.
D/(16:17:20.295) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Network request execution took 107.285365ms.
D/(16:17:20.295) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Json reading took 6.654531ms.
D/(16:17:20.295) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Store new posts took 834.687us (stored 1 posts).
D/(16:17:20.295) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Parse posts took 485us (parsed 1 out of 38 posts).
D/(16:17:20.295) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Filter processing took 3.021us (filers count: 0).
D/(16:17:20.295) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Total in-memory cached posts count: 551/13107.
D/(16:17:20.295) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Current thread cached posts count: 38
D/(16:17:20.295) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Threads with more than one post count: (4/8), total cached threads count: 351.
D/(16:17:20.295) KurobaEx-fdroid | ChanThreadLoaderCoordinator: Total local processing time: 7.977239ms
D/(16:17:20.296) KurobaEx-fdroid | ThreadDataPreloadUseCase: postloadThreadInfo(TD{4chan/v/590201574}) begin
D/(16:17:20.296) KurobaEx-fdroid | ThreadDataPreloadUseCase: postloadThreadInfo(TD{4chan/v/590201574}) end
D/(16:17:20.296) KurobaEx-fdroid | ChanThreadManager: loadThreadOrCatalog(), descriptor=TD{4chan/v/590201574} postloadThreadInfo took 199.948us
D/(16:17:20.296) KurobaEx-fdroid | ThreadPresenter: normalLoad() threadLoadResult=ThreadLoadResult.Loaded{chanDescriptor=TD{4chan/v/590201574}} (currentChanDescriptor=TD{4chan/v/590201574})
D/(16:17:20.296) KurobaEx-fdroid | ThreadPresenter: onChanLoaderData() called, loadedChanDescriptor=TD{4chan/v/590201574}
D/(16:17:20.296) KurobaEx-fdroid | ChanTicker: kickTicker(false)
D/(16:17:20.296) KurobaEx-fdroid | KotlinExts: awaitUntilGloballyLaidOut(com.github.k1rakishou.chan.ui.view.LoadView{26fb426 V.E...... ........ 0,0-1080,2280 #7f0a01f6 app:id/loadview}) widthOk=true, width=1080, heightOk=true, height=2280
D/(16:17:20.297) KurobaEx-fdroid | ChanTicker: StartOrResetTicker chanDescriptor=TD{4chan/v/590201574}
D/(16:17:20.297) KurobaEx-fdroid | ChanTicker: startOrRestartTickerInternal scheduled, chanDescriptor=TD{4chan/v/590201574}, waiting 60000ms
D/(16:17:20.298) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() ApplyingFilters(chanDescriptor=TD{4chan/v/590201574}, postHidesCount=0, postFiltersCount=0)
D/(16:17:20.298) KurobaEx-fdroid | PostHideHelper: processPostFilters(TD{4chan/v/590201574}) start
D/(16:17:20.298) KurobaEx-fdroid | PostHideHelper: processPostFilters(TD{4chan/v/590201574}) end (hiddenPostsCount=0, removedPostsCount=0, normalPostsCount=38, total=38)
D/(16:17:20.299) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() RefreshingPosts(chanDescriptor=TD{4chan/v/590201574})
D/(16:17:20.301) KurobaEx-fdroid | PostAdapter: setThread() notifyDataSetChanged called, postIndexedList.size=38
D/(16:17:20.301) KurobaEx-fdroid | ThreadLayout: showPostsForChanDescriptor() showPosts(TD{4chan/v/590201574}) -> true applyFilterDuration=1.115365ms, setThreadPostsDuration=2.314218ms, totalDuration=4.513333ms
D/(16:17:20.301) KurobaEx-fdroid | ThreadPresenter: onChanLoaderData(TD{4chan/v/590201574}) end, took 5.423490ms
D/(16:17:20.302) KurobaEx-fdroid | ThreadPresenter: normalLoad() end
D/(16:17:20.302) KurobaEx-fdroid | ThreadLayout: handleLoadProgressEvent() End(chanDescriptor=TD{4chan/v/590201574})
D/(16:17:20.302) KurobaEx-fdroid | ThreadCellData: runPreloading() start
D/(16:17:20.302) KurobaEx-fdroid | ThreadCellData: runPreloading() startingPosition=0, dataListSize=38
D/(16:17:20.303) KurobaEx-fdroid | HistoryNavigationManager: persistNavigationStack async called
D/(16:17:20.303) KurobaEx-fdroid | HistoryNavigationManager: persistNavigationStackInternal navStackCopy.size=259
D/(16:17:20.304) KurobaEx-fdroid | NavHistoryLocalSource: persist(navHistoryStack.size=259)
D/(16:17:20.311) KurobaEx-fdroid | ThreadCellData: runPreloading() end, took 8.683073ms
D/(16:17:20.329) KurobaEx-fdroid | HistoryNavigationRepository: persist(259) took 25.275364ms
D/(16:17:20.330) KurobaEx-fdroid | HistoryNavigationManager: persistNavigationStack async finished
D/(16:17:49.580) KurobaEx-fdroid | BookmarkWatcherCoordinator: restartBackgroundWork() called tag=BookmarkWatcherController_Fdroid
D/(16:17:49.580) KurobaEx-fdroid | BookmarkWatcherCoordinator: restartBackgroundWork() cannot restart watcher because one of the required settings is turned off (watchEnabled=true, watchBackground=false)
D/(16:17:49.580) KurobaEx-fdroid | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() called tag=BookmarkWatcherController_Fdroid
D/(16:17:49.584) KurobaEx-fdroid | BookmarkWatcherCoordinator: cancelBackgroundBookmarkWatching() work with tag BookmarkWatcherController_Fdroid canceled
D/(16:17:49.584) KurobaEx-fdroid | BookmarkWatcherDelegate: awaitUntilAllDependenciesAreReady()...
D/(16:17:49.584) KurobaEx-fdroid | BookmarkWatcherDelegate: awaitUntilAllDependenciesAreReady()...done
D/(16:17:49.584) KurobaEx-fdroid | BookmarkWatcherDelegate: doWorkInternal() updating 5 bookmarks
D/(16:17:49.584) KurobaEx-fdroid | LastPageNotificationsHelper: showOrUpdateNotifications(5)
D/(16:17:49.584) KurobaEx-fdroid | LastPageNotificationsHelper: ChanSettings.watchLastPageNotify is disabled
D/(16:17:49.584) KurobaEx-fdroid | BookmarkWatcherDelegate: BookmarkWatcherDelegate.doWork() called, isCalledFromForeground=true, currentThreadDescriptor=TD{4chan/v/590201574}
D/(16:17:49.585) KurobaEx-fdroid | FetchThreadBookmarkInfoUseCase: FetchThreadBookmarkInfoUseCase.execute(5)
D/(16:17:49.815) KurobaEx-fdroid | BookmarkWatcherDelegate: fetchThreadBookmarkInfo stats: total results=5, errorsCount=0, alreadyDeletedCount=0, notFoundOnServerCount=0, badStatusCount=0, successCount=5
D/(16:17:49.837) KurobaEx-fdroid | BookmarkWatcherDelegate: BookmarkWatcherDelegate.doWork() success, activeBookmarksCount=5
D/(16:17:49.850) KurobaEx-fdroid | BookmarkWatcherDelegate: BookmarkWatcherDelegate.doWork() took 265.797135ms
D/(16:17:50.852) KurobaEx-fdroid | ReplyNotificationsHelper: showOrUpdateNotificationsInternal() ChanSettings.replyNotifications == false
E/(16:18:05.950) KurobaEx-fdroid | Chan: Unhandled exception in thread: main
E/(16:18:05.950) KurobaEx-fdroid | Chan: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 357332 bytes
E/(16:18:05.950) KurobaEx-fdroid | Chan: 	at android.view.autofill.AutofillManager.updateSessionLocked(AutofillManager.java:1975)
E/(16:18:05.950) KurobaEx-fdroid | Chan: 	at android.view.autofill.AutofillManager.notifyViewEnteredLocked(AutofillManager.java:1098)
E/(16:18:05.950) KurobaEx-fdroid | Chan: 	at android.view.autofill.AutofillManager.notifyViewEntered(AutofillManager.java:1048)
E/(16:18:05.950) KurobaEx-fdroid | Chan: 	at android.view.autofill.AutofillManager.notifyViewEntered(AutofillManager.java:1005)
E/(16:18:05.950) KurobaEx-fdroid | Chan: 	at android.view.View.notifyEnterOrExitForAutoFillIfNeeded(View.java:8501)
E/(16:18:05.950) KurobaEx-fdroid | Chan: 	at android.view.View.performClick(View.java:7800)
E/(16:18:05.950) KurobaEx-fdroid | Chan: 	at android.widget.TextView.performClick(TextView.java:16045)
E/(16:18:05.950) KurobaEx-fdroid | Chan: 	at android.view.View.performClickInternal(View.java:7769)
E/(16:18:05.950) KurobaEx-fdroid | Chan: 	at android.view.View.access$3800(View.java:910)
E/(16:18:05.950) KurobaEx-fdroid | Chan: 	at android.view.View$PerformClick.run(View.java:30184)
E/(16:18:05.950) KurobaEx-fdroid | Chan: 	at android.os.Handler.handleCallback(Handler.java:938)
E/(16:18:05.950) KurobaEx-fdroid | Chan: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/(16:18:05.950) KurobaEx-fdroid | Chan: 	at android.os.Looper.loopOnce(Looper.java:226)
E/(16:18:05.950) KurobaEx-fdroid | Chan: 	at android.os.Looper.loop(Looper.java:313)
E/(16:18:05.950) KurobaEx-fdroid | Chan: 	at android.app.ActivityThread.main(ActivityThread.java:8641)
E/(16:18:05.950) KurobaEx-fdroid | Chan: 	at java.lang.reflect.Method.invoke(Native Method)
E/(16:18:05.950) KurobaEx-fdroid | Chan: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
E/(16:18:05.950) KurobaEx-fdroid | Chan: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
E/(16:18:05.950) KurobaEx-fdroid | Chan: Caused by: android.os.TransactionTooLargeException: data parcel size 357332 bytes
E/(16:18:05.950) KurobaEx-fdroid | Chan: 	at android.os.BinderProxy.transactNative(Native Method)
E/(16:18:05.950) KurobaEx-fdroid | Chan: 	at android.os.BinderProxy.transact(BinderProxy.java:635)
E/(16:18:05.950) KurobaEx-fdroid | Chan: 	at android.view.autofill.IAutoFillManager$Stub$Proxy.updateSession(IAutoFillManager.java:737)
E/(16:18:05.950) KurobaEx-fdroid | Chan: 	at android.view.autofill.AutofillManager.updateSessionLocked(AutofillManager.java:1972)
E/(16:18:05.950) KurobaEx-fdroid | Chan: 	... 17 more


------------------------------
Android API Level: 31
App Version: v1.3.8
Phone Model: samsung SM-G970U
Build type: Unknown
Flavor type: Fdroid
isLowRamDevice: false, isLowRamDeviceForced: false
MemoryClass: 256
App running time: 00:08:44.178
------------------------------
Current layout mode: SLIDE
Board view mode: GRID
Bottom navigation enabled: true
Prefetching enabled: false
Hi-res thumbnails enabled: false
mediaViewerMaxOffscreenPages: 2
CloudFlare force preload enabled: false
useMpvVideoPlayer: false
userAgent: Mozilla/5.0 (Linux; Android 12; SM-G970U Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/98.0.4758.101 Mobile Safari/537.36
kurobaExCustomUserAgent: KurobaEx-fdroid v1.3.8
maxPostsCountInPostsCache: 13107
maxAmountOfPostsInDatabase: 75000
maxAmountOfThreadsInDatabase: 12500
diskCacheSizeMegabytes: 256
prefetchDiskCacheSizeMegabytes: 512
diskCacheCleanupRemovePercent: 25
ImageSaver root directory: content://com.android.externalstorage.documents/tree/primary%3AClover
OkHttp IPv6 support enabled: false
OkHttp HTTP/2 support enabled: true
Foreground watcher enabled: true
Watch foreground interval: 60000
Watch foreground adaptive interval: false
Background watcher enabled: false
Filter watch enabled: true
Filter watch interval: 43200000
Thread downloader interval: 3600000
Thread downloader download media on metered network: false
------------------------------
```

**Comment by K1rakishou** [comment] 2022-02-27 11:20
Duplicate of https://github.com/KurobaExReports/Reports/issues/173

**Closed by K1rakishou** 2022-02-27 11:20 UTC
Labels: Crash
